### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Darkcast** [Chungwin/JobCrawler#1]
Why parse the html when you get the data in json using their api?

**Comment by Chungwin** [comment]
Well, I think I fell in love with the idea of learning how to crawl pages and went with it. I still like the idea. 

However, you are right. Haven't really checked out their API. But I think what prevented me from going with their API is, that a) the API gives out max. 25 pages per site and b) can be accessed just once per hour. 

To get a holistic idea of the job market in a region, I want to go through all 30.000 jobs in a city.
